routes/web.php
<?php
use Illuminate\Support\Facades\DB;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



/*
* Home & Web
*/

Route::get('/', function () {
    $posts = App\Post::all();
    $products = App\products::all();
    return view('welcome', compact('posts','products'));
});
Route::get('contacto', function(){
    return view('contacto');
});




/*
* Auth
*/
Auth::routes();
//Route::get('/home', 'HomeController@index')->name('home');




/*
* Registro usuario
*/
Route::get('register','Auth\RegisterController@create');
Route::post('register','Auth\RegisterController@create');

Route::group(['prefix' => 'admin'], function () {
    Voyager::routes();
});




/*
* post
*/
Route::get('post/{slug}', function($slug){
    $post = App\Post::where('slug', '=', $slug)->firstOrFail();
    return view('post', compact('post'));
});




/*
* Products
*/
Route::get('plato/{id}', function($id){
    $product = App\products::where('id', '=', $id)->firstOrFail();
    return view('products', compact('product'));
});




/*
* Categories
*/
Route::get('category/{id}', function($id){
//    SELECT * FROM products as p INNER JOIN categories as c WHERE c.id = 1
    $category = DB::select( DB::raw('SELECT * FROM products WHERE category_id = '.$id) );
//    $category = App\products::where('category_id', '=', $id)->firstOrFail();
    return view('categories', compact('category'));
});




/*
* Route Cart
*/

Route::resource('cart','Carts');
Route::get('empty',function(){
    Cart::destroy();
});
Route::resource('delete', 'Carts');

Route::post('process', function () {
    return view('cart');
});

Route::get('sales', function () {
    return view('sales');
});

resources/views/cart.blade.php
<?php
/**
 * Created by PhpStorm.
 * User: lamnav
 * Date: 9/9/2018
 * Time: 00:59
 */

$total = 0;
$subtotal = 0;
?>


@include('headerFront')
<style>
body {
    height: 100%;
}
.input-group{
  width: 130px;
  margin: 0 auto;
}
.fa-plus, .fa-minus{
  color: #f52f41;
}
.total {
    width: 100px;
    border: none;
    background: transparent;
}
.no-articles {
  margin: 150px auto;
}
</style>
<div style="position: relative; overflow: hidden; margin-bottom: 20px">
    <div class="progressive-image_container" style="position: absolute; width: 100%; height: 100%;">
        <img src="{{ asset('images/bg_header.png') }}"
             style="width: 100%; height: 100%; transition: -webkit-filter 1.5s ease 0s;">
    </div>
    <div style="position: relative;">
        <section class="ui container _1aP3Hvrg71IsrTM22x8W6m" style="height:20.5rem!important;"><h1
                class="ch2Gspxs_6Su97s_BWokH">Carrito</h1>
        </section>
    </div>
</div>

<div class="cart-section container">
        <div>
            @if (session()->has('success_message'))
                <div class="alert alert-success">
                    {{ session()->get('success_message') }}
                </div>
            @endif

            @if(count($errors) > 0)
                <div class="alert alert-danger">
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif


            @if (Cart::count() > 0)

            <h4>{{ Cart::count() }} item(s) en el carrito</h4>

            <table class='table table-hover table-responsive'>
                <thead>
                <tr>
                    <th class='thead' width="15%"></th>
                    <th class='textAlignLeft thead'>Nombre del producto</th>
                    <th class="thead">Precio</th>
                    <th class="thead text-center">Cantidad</th>
                    <th class="thead">Sub Total</th>
                    <th class="thead"></th>
                </tr>
                </thead>
                <tbody>


                @foreach (Cart::content() as $item)

                <tr>
                        <td class="text-center">
                            {{-- <img src="{{ asset('images/no-image.png') }}" alt="" width="100px" class="text-center"> --}}
                            {{-- @if(file_exists( Voyager::image( $item->image ) ))
                                <img src="{{ Voyager::image( $item->image ) }}" alt="" width="100px" class="text-center">
                            @else
                                <img src="{{ asset('images/no-image.png') }}" alt="" width="100px" class="text-center">
                            @endif --}}
                            @if(!empty( Voyager::image( $item->model->image ) ))
                                <img src="{{ Voyager::image( $item->model->image ) }}" style="width:70%">
                            @else
                                <img src="{{ asset( 'images/no-image.png' ) }}" style="width:70%">
                            @endif
                        </td>
                        <td>
                            <div class='product-id' style='display:none;'>7</div>
                            <div class='product-name'>{{ ucwords($item->model->name) }}</div>
                            <div style="font-size: 11px">{{ ucwords($item->model->details) }}</div>
                        </td>
                        <td class="precio">&#36;{{ $item->model->price }}

                        <td>
                            <div class='input-group'>
                                <input type="hidden" class="price" value="{{ $item->model->price }}" id="price" name="price">
                                <div class="input-group">
                                    <span class="input-group-btn">
                                        <button type="button" class="btn btn-default btn-number"  data-type="minus" data-field="quantity[1]" style="margin-top: 0px; padding: 5px 10px;">
                                            <span class="fas fa-minus"></span>
                                        </button>
                                    </span>
                                    <input type="text" name="quantity[1]" id="quantity" class="form-control input-number text-center" value="{{ $item->qty }}" min="1" max="10" >
                                    <span class="input-group-btn">
                                        <button type="button" class="btn btn-default btn-number" data-type="plus" data-field="quantity[1]" style="margin-top: 0px; padding: 5px 10px;">
                                            <span class="fas fa-plus"></span>
                                        </button>
                                    </span>
                                </div>
                            </div>
                        </td>
                        <td>&#36; <input type="text" id="subtotal" data-type="subtotal" readonly="" class="total" value="{{ $item->model->price * $item->qty }}"></td>
                        <td>
                           {{--  @include('cart.delete') --}}
                           <form action="{{ route('cart.destroy', $item->rowId) }}" method="POST">
                                {{ csrf_field() }}
                                {{ method_field('DELETE') }}

                                <button type="submit" class="cart-options">Remover</button>
                            </form>
                            <form action="/" method="POST">
                                {{ csrf_field() }}

                                <button type="submit" class="cart-options">Guardar</button>
                            </form>
                        </td>
                    </tr>

                @endforeach
                <tr class="total">
                    <td colspan="3"></td>
                    <td><b>Subtotal</b></td>
                    <td> &#36;{{ Cart::subtotal() }}</td>
                    <td></td>
                </tr>
                <tr class="total">
                    <td colspan="3"></td>
                    <td><b>Tax (13%)</b></td>
                    <td> &#36;{{ Cart::tax() }}</td>
                    <td></td>
                </tr>
                <tr class="total">
                    <td colspan="3"></td>
                    <td><b>Costo envío</b></td>
                    <td> <input type="hidden" readonly="" class="total" value="17.00" id="envio">&#36;17,00</td>
                    <td></td>
                </tr>
                <tr class="total">
                    <td colspan="3"></td>
                    <td><b>Total</b></td>
                    <td>&#36;{{ Cart::total() }}</td>
                    <td></td>
                </tr>

                </tbody>
            </table>
            </div> <!-- end cart-table -->

            <div class="spacer"></div>
            <a href="/" class="btn btn-primary" style="margin-right: 20px"><i class="fas fa-shopping-basket"></i> Seguir comprando</a>

            <a href="/" class="btn btn-primary" style="margin-right: 20px"><i class="fas fa-shopping-cart" style="font-size: 1em"></i> Procesar compra</a>
            <div class="spacer"></div>

            @else

                <div class="no-articles text-center">
                  <h4>No hay artículos cargados en el Carrito</h4>
                    <div class="spacer"></div>
                    <a href="/" class="btn btn-primary" style="margin-right: 20px"><i class="fas fa-shopping-basket"></i> Seguir comprando</a>
                    <div class="spacer"></div>
                </div>

            @endif



    </div>
</div>

@include('footer')

<script>
    $(document).ready(function(){
        $('.btn-number').click(function(e) {
          e.preventDefault();

          fieldName = $(this).attr('data-field');
          type = $(this).attr('data-type');
          var input = $("input[name='" + fieldName + "']");
          var currentVal = parseInt(input.val());
          m1 = document.getElementById("price").value;
          envio = document.getElementById("envio").value;

          if (type == "minus") {
            var inputminus = $(this).parent().next();
            var subtotal = $(this).parent().parent().parent().next();
            if (parseInt(inputminus.val()) != 0) {
                inputminus.val(parseInt(inputminus.val())-1);
console.log(subtotal);

                subtotal = parseFloat(subtotal) * parseInt(input.val());
          document.getElementById("subtotal").value = subtotal;

                total = parseFloat(subtotal)+parseFloat(envio);
          document.getElementById("total").value = total;
            }
          }
          else {
            var input = $(this).parent().prev();
            var inputQty = parseInt(input.val());
            input.val(inputQty+1);

            subtotal = parseFloat(m1) * parseInt(input.val());
          document.getElementById("subtotal").value = subtotal;

           total = parseFloat(subtotal)+parseFloat(envio);
          document.getElementById("total").value = total;
            
          }

        // console.log($(this).parent().prev().val());















          // if (!isNaN(currentVal)) {
          //   if (type == 'minus') {

          //     if (currentVal > input.attr('min')) {
          //       input.val(currentVal - 1).change();
          //     }
          //     if (parseInt(input.val()) == input.attr('min')) {
          //       $(this).attr('disabled', true);
          //     }

          //   } else if (type == 'plus') {

          //     if (currentVal < input.attr('max')) {
          //       input.val(currentVal + 1).change();
          //     }
          //     if (parseInt(input.val()) == input.attr('max')) {
          //       $(this).attr('disabled', true);
          //     }

          //   }
          // } else {
          //   input.val(0);
          // }
        });
        $('.input-number').focusin(function() {
          $(this).data('oldValue', $(this).val());
        });
        $('.input-number').change(function() {

          minValue = parseInt($(this).attr('min'));
          maxValue = parseInt($(this).attr('max'));
          valueCurrent = parseInt($(this).val());
          

          name = $(this).attr('name');
          if (valueCurrent >= minValue) {
            $(".btn-number[data-type='minus'][data-field='" + name + "']").removeAttr('disabled')
          } else {
            alert('Sorry, the minimum value was reached');
            $(this).val($(this).data('oldValue'));
          }
          if (valueCurrent <= maxValue) {
            $(".btn-number[data-type='plus'][data-field='" + name + "']").removeAttr('disabled')
          } else {
            alert('Sorry, the maximum value was reached');
            $(this).val($(this).data('oldValue'));
          }
          


        });




    });
</script>

resources/views/categories.blade.php
<?php
/**
 * Created by PhpStorm.
 * User: lamnav
 * Date: 11/9/2018
 * Time: 00:53
 */

$id = request()->segment(count(request()->segments()));
$categories = App\Category::where('id', '=', $id)->firstOrFail();
$categoriess = App\Category::all();
?>


@include('headerFront')

<div style="position: relative; overflow: hidden; margin-bottom: 20px">
    <div class="progressive-image_container" style="position: absolute; width: 100%; height: 100%;">
        <img src="{{ asset('images/bg_header.png') }}"
             style="width: 100%; height: 100%; transition: -webkit-filter 1.5s ease 0s;">
    </div>
    <div style="position: relative;">
        <section class="ui container _1aP3Hvrg71IsrTM22x8W6m" style="height:20.5rem!important;">
            <h1 class="ch2Gspxs_6Su97s_BWokH">{{ ucwords($categories->name) }}</h1>
        </section>
    </div>
</div>

<div class="container">
    <div class="row">
        <div>
           <div style="float: left;">
               @foreach($category as $categoryes)
                   <div class="products_box" style="margin-bottom: 20px; width: 40%;">
                       <a href="/plato/{{ $categoryes->id }}">
                           <div class="image_product">
                               <img src="{{ Voyager::image( $categoryes->image ) }}" style="float: left; margin-top: 0px; width: 100%; height: 100%">
                           </div>
                           <div class="content-info">
                               <span class="nameProduct">{{ ucwords($categoryes->name) }}</span>
                               <span class="descProduct">{{ $categoryes->description }}</span>
                               <span class="priceProduct">$RD {{ $categoryes->price }}</span>
                               <div class="ec-stars-wrapper">
                                   <a href="#" data-value="1" title="Votar con 1 estrellas">&#9733;</a>
                                   <a href="#" data-value="2" title="Votar con 2 estrellas">&#9733;</a>
                                   <a href="#" data-value="3" title="Votar con 3 estrellas">&#9733;</a>
                                   <a href="#" data-value="4" title="Votar con 4 estrellas">&#9733;</a>
                                   <a href="#" data-value="5" title="Votar con 5 estrellas">&#9733;</a>
                               </div>
                               <noscript>Necesitas tener habilitado javascript para poder votar</noscript>
                           </div>
                       </a>
                   </div>
               @endforeach


           </div>
        </div>
    </div>
</div>


@include('footer')

resources/views/checkout.blade.php
<?php
/**
 * Created by PhpStorm.
 * User: lamnav
 * Date: 25/9/2018
 * Time: 17:10
 */
?>
@include('headerFront')

<style>
    .description {
        font-size: 12px;
        text-align: justify;
    }
</style>

{{-- Background Header --}}
<div style="position: relative; overflow: hidden; margin-bottom: 20px">
    <div class="progressive-image_container" style="position: absolute; width: 100%; height: 100%;">
        <img src="{{ asset('images/bg_header.png') }}"
             style="width: 100%; height: 100%; transition: -webkit-filter 1.5s ease 0s;">
    </div>
    <div style="position: relative;">
        <section class="ui container _1aP3Hvrg71IsrTM22x8W6m" style="height:20.5rem!important;"><h1
                class="ch2Gspxs_6Su97s_BWokH">Checkout - Detalles de compra</h1>
        </section>
    </div>
</div>
{{-- Background Header --}}


{{-- Body --}}
<div class="container">

    @if (session()->has('success_message'))
        <div class="spacer"></div>
        <div class="alert alert-success">
            {{ session()->get('success_message') }}
        </div>
    @endif

    @if(count($errors) > 0)
        <div class="spacer"></div>
        <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{!! $error !!}</li>
                @endforeach
            </ul>
        </div>
    @endif

    <div class="">
        <div class="container" style="margin-bottom: 50px">
            <div class="row">
                <div class="col-md-6">

                    @if (Auth::guest())
                        <h2 class="text-center">Ya soy cliente</h2>
                        <hr>
                        <div class="col-md-6" style="padding-left: 0!important; padding-right: 0!important">
                            <form action="/">
                                {{--<button class="btn google-login"><i class="fab fa-google"></i> Login con Google</button>--}}

                                <a class="btn btn-block btn-social btn-google" style="color: #ffffff">
                                    <span class="fab fa-google"></span> Login con Google
                                </a>
                            </form>
                        </div>
                        <div class="col-md-6" style="padding-left: 0!important; padding-right: 0!important">
                            <form action="/">
                                {{--<button class="btn facebook-login"><i class="fab fa-facebook-f"></i> Login con facebook</button>--}}
                                <a class="btn btn-block btn-social btn-facebook" style="color: #ffffff">
                                    <span class="fab fa-facebook"></span> Login con Facebook
                                </a>
                            </form>
                        </div>
                        <form action="{{ route('login') }}" method="POST">
                            {{ csrf_field() }}
                            <div class="form-group form-group-default" id="emailGroup">
                                <label>{{ __('voyager::generic.email') }}</label>
                                <div class="controls">
                                    <input type="text" name="email" id="email" value="{{ old('email') }}"
                                           placeholder="{{ __('voyager::generic.email') }}" class="form-control" required>
                                </div>
                            </div>

                            <div class="form-group form-group-default" id="passwordGroup">
                                <label>{{ __('voyager::generic.password') }}</label>
                                <div class="controls">
                                    <input type="password" name="password" placeholder="{{ __('voyager::generic.password') }}"
                                           class="form-control" required>
                                </div>
                            </div>
                            <button type="submit" class="btn btn-block login-button" style="margin-right: 20px; float: left; width: 48%; color: #ffffff">
                                <span class="signingin hidden">
                                    <span class="voyager-refresh"></span> {{ __('voyager::login.registring') }}...</span>
                                <span class="signin">{{ __('voyager::generic.login') }}</span>
                            </button>
                            <button type="button" class="btn btn-block login-button" data-toggle="modal" data-target="#myModal" style="float: left; width: 48%; color: #ffffff">
                                <span class="signin">{{ __('general.registry') }}</span>
                            </button>
                        </form>

                        @if (session()->has('success_message'))
                            <div class="alert alert-green">
                                <ul class="list-unstyled">
                                    <li>{{ session()->get('success_message') }}</li>
                                </ul>
                            </div>
                        @endif
                    @else
                        <h2>Detalles de envío</h2>
                        <form action="{{ route('checkout.store') }}" method="POST">
                            {{ csrf_field() }}
                            <div class="form-group">
                                <label for="email">Email</label>
                                <input type="email" class="form-control" name="email" id="email" value="{{ auth()->user()->email }}"
                                       placeholder="Introduce tu email">
                            </div>
                            <div class="form-group">
                                <label for="name">Nombre y Apellido</label>
                                <input type="text" class="form-control" name="name" id="name" value="{{ auth()->user()->name }}"
                                       placeholder="Introduce tu nombre">
                            </div>
                            <div class="form-group">
                                <label for="telefono">Teléfono</label>
                                <input type="text" class="form-control" maxlength="11" data-mask="(000) 0000-0000" name="phone" id="telefono" value="{{ auth()->user()->phone }}"
                                       placeholder="Introduce tu teléfono" required>
                            </div>
                            <div class="form-group">
                                <label for="address">Dirección de entrega</label>
                                <textarea type="text" class="form-control" name="address" id="address"
                                          placeholder="Introduce tu dirección" required></textarea>
                            </div>
                            <div style="float: right;">
                                <a href="/" class="btn btn-primary" style="margin-right: 20px">
                                    <i class="fas fa-shopping-basket"></i> Seguir comprando
                                </a>
                                <button type="submit" class="btn btn-danger">
                                    <i class="fas fa-shopping-cart" style="font-size: 1em"></i> Completar pedido
                                </button>
                            </div>
                        </form>

                    @endif

                </div>
                <div class="col-md-6">
                    <h2 class="text-center">Resumen del pedido</h2>
                    <hr>
                    <table class='table table-hover table-responsive'>
                        <thead>
                        <tr>
                            <th class='thead' width="15%"></th>
                            <th class='textAlignLeft thead'></th>
                            <th class="thead" style="float: right">Cantidad</th>
                        </tr>
                        </thead>
                        <tbody>

                        @foreach (Cart::content() as $item)

                            <tr>
                                <td class="text-center">

                                    @if(!empty( Voyager::image( $item->model->image ) ))
                                        <img src="{{ Voyager::image( $item->model->image ) }}" >
                                    @else
                                        <img src="{{ asset( 'images/no-image.png' ) }}" >
                                    @endif

                                </td>
                                <td>
                                    <strong>{{ $item->model->name }}</strong>
                                    <br>
                                    <p class="description">{{ ucwords($item->model->description) }}</p>
                                    <p>&#36;{{ $item->model->price }}</p>
                                </td>
                                <td >
                                    <div class='input-group' style="float: right">

                                        <input type="text" name="quantity[1]" id="quantity"
                                               class="form-control input-number text-center"
                                               value="{{ $item->qty }}" min="1"
                                               max="10" style="width: 50px">
                                    </div>
                                </td>
                            </tr>


                        @endforeach

                        <tr class="total" style="text-align: right;">
                            <td></td>
                            <td>
                                <b>Subtotal:</b><br>
                                <b>Tax (13%):</b><br>
                                <b>Costo envío:</b><br>
                                <b>Total:</b>
                            </td>
                            <td>
                                <?php
                                $subtotal = str_replace(',', '.', Cart::total());
                                $ShippingCost = config('cart.ShippingCost');
                                $total = $subtotal + $ShippingCost;
                                ?>
                                &#36;{{ Cart::subtotal() }}<br>
                                &#36;{{ Cart::tax() }}<br>
                                &#36;{{ $ShippingCost }}<br>
                                &#36;{{ str_replace('.', ',', $total) }}
                            </td>
                        </tr>

                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
{{-- Body --}}


@include('footer')

resources/views/footer.blade.php
<footer class="content_module new_row new_footer show text-center">
    <div class="row" style="max-width: 80%; margin: 0 auto;">
        <div class="col-md-4">
            <ul style="list-style-type: none;">
                <li>
                    Nosotros
                </li>
                <li>
                    <a href="/contacto">Contacto</a>
                </li>
                <li>
                    Sé parte de iZabor
                </li>
            </ul>
        </div>
        <div class="col-md-4">
            <label for="gplay">Descargar app</label><br>
            <a href="https://play.google.com/store/apps/developer?id=Luis+Armando+Mar%C3%ADn" target="_blank">
                <img src="{{ asset('images/mob-button-gplay.png') }}" alt="Disponible en Google Play" style="max-width: 40%!important">
            </a>
        </div>
        <div class="col-md-4 ">
            <label for="social">Siguenos:</label><br>
            <div>
                <ul class="content_social">
                    <li><a href="https://fb.com/izabor" target="_blank"><i class="fab fa-facebook-f"></i></a></li>
                    <li><a href="https://instagram.com/izabor" target="_blank"><i class="fab fa-instagram"></i></a></li>
                    <li><a href="https://twitter.com/izabor" target="_blank"><i class="fab fa-twitter"></i></a></li>
                </ul>
            </div>
        </div>
    </div>
    <div class="text-center footer" style="font-size: .8em">
        &copy; Copyright {{ date('Y') }} - <a href="#"><b>iZabor</b></a> Diseño y Desarrollo con <i class="fa fa-heart heart"></i> <a href="//marinluis.com" target="_blank">Luis Marín</a>
    </div>
</footer>


{{-- Scripts --}}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

<script>
    {{-- Tolltip --}}
    $(document).ready(function(){
        $('[data-toggle="tooltip"]').tooltip()
    })
</script>

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

{{--<!DOCTYPE html>--}}
{{--<html>--}}
{{--<head>--}}
    {{--<title>Homepage</title>--}}
    {{--<link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/css/bootstrap.min.css">--}}
{{--</head>--}}
{{--<body>--}}

{{--<div class="container">--}}
    {{--<br><br>--}}
    {{--<div class="row">--}}
        {{--@foreach($posts as $post)--}}
            {{--<div class="col-md-3">--}}
                {{--<a href="/post/{{ $post->slug }}">--}}
                    {{--<img src="{{ Voyager::image( $post->image ) }}" style="width:100%">--}}
                    {{--<span>{{ $post->title }}</span>--}}
                {{--</a>--}}
            {{--</div>--}}
        {{--@endforeach--}}
    {{--</div>--}}
{{--</div>--}}

{{--</body>--}}
{{--</html>--}}

resources/views/notificacion.blade.php
Ingresa a más tutoriales en <a href="{{ $link }}">{{ $link }}</a>

resources/views/orders.blade.php
<?php
/**
 * Created by PhpStorm.
 * User: lamnav
 * Date: 25/9/2018
 * Time: 17:11
 */

@include('headerFront');

resources/views/post.blade.php
<!DOCTYPE html>
<html>
<head>
    <title>{{ $post->title }}</title>
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/css/bootstrap.min.css">
</head>
<body>

<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">

            <h1>{{ $post->title }}</h1>
            <img src="{{ Voyager::image( $post->image ) }}" style="width:100%">
            <p>{!! $post->body !!}</p>

        </div>
    </div>
</div>

</body>
</html>